spring:

  datasource: ## 數據源配置
             driverClassName: com.mysql.jdbc.Driver
             url: jdbc:mysql://localhost:3306/springbootdb?useSSL=false
             username: root
             password: 999999    
  redis: 
        # database的配置通常使用0即可，Redis在配置的時候可以設置數據庫數量，默認為16，可以理解為數據庫的schema
        database: 0 # redis數據庫索引（默認為0）
        host: localhost # redis服務器地址（默認為localhost）
        port: 6379 # redis端口（默認為6379）
        password: # redis訪問密碼（默認為空）
        timeout: 0 # redis連接超時時間（單位為毫秒）
        pool:      # redis連接池配置
             max-active: 8  # 最大可用連接數（默認為8，負數表示無限）
             max-idle: 8 # 最大空閒連接數（默認為8，負數表示無限）
             min-idle: 0 # 最小空閒連接數（默認為0，該值只有為正數才有作用）
             max-wait: -1 # 從連接池中獲取連接最大等待時間（默認為-1，單位為毫秒，負數表示無限）     


# Mybatis 配置
 
mybatis:
        mapperLocations: classpath:mapper/*.xml
        typeAliasesPackage: com.errui.domain         